version: '3.7'

services:
  app:
    build: .
    command: sleep infinity
    volumes:
      - ../:/go/src/app:cached
  db:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=echo_db
    ports:
      - 3306:3306